// Generated by .verify/gen-security-vectors.mjs — do not edit by hand.
//
// Pins the shared endpoint-policy behaviour for this plugin in both modes. The
// vectors come from the canonical .verify/security-vectors.json in the workspace
// root, so a plugin whose address handling drifts fails here, in its own CI.
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { guardEndpoint } from '../src/url-security.js'

interface SecurityVector {
  host: string
  why: string
  lenient: 'allow' | 'block'
  strict: 'allow' | 'block'
}

const { cases } = JSON.parse(
  readFileSync(new URL('./security-vectors.json', import.meta.url), 'utf8'),
) as { cases: SecurityVector[] }

const toRawUrl = (host: string) => `http://${host.includes(':') ? `[${host}]` : host}/`

const verdict = async (host: string, enforcePublicEndpoint: boolean): Promise<'allow' | 'block'> =>
  (await guardEndpoint(toRawUrl(host), { enforcePublicEndpoint })) === undefined ? 'allow' : 'block'

describe('security vectors (tiered endpoint policy)', () => {
  it('carries the full canonical vector set', () => {
    expect(cases.length).toBeGreaterThanOrEqual(50)
  })

  it.each(cases)('$host ($why) defaults to $lenient and is $strict when enforcing', async vector => {
    expect(await verdict(vector.host, false)).toBe(vector.lenient)
    expect(await verdict(vector.host, true)).toBe(vector.strict)
  })
})
